### ISSUE TITLE
Previewing theme issue

### ISSUE THREAD

**Issue by pellens** [zendesk/copenhagen_theme#20]
When previewing the theme with `zat theme preview`, the first load is working well.
When editing my code, the preview or reload is not working anymore.

I get the following message when exiting the zat preview mode:

```Unexpected error while processing request: eventmachine not initialized: evma_send_data_to_connection
	/Library/Ruby/Gems/2.3.0/gems/eventmachine-1.2.5/lib/em/connection.rb:328:in `send_data'
	/Library/Ruby/Gems/2.3.0/gems/eventmachine-1.2.5/lib/em/connection.rb:328:in `send_data'
	/Library/Ruby/Gems/2.3.0/gems/thin-1.7.2/lib/thin/connection.rb:116:in `block in post_process'
	/Library/Ruby/Gems/2.3.0/gems/thin-1.7.2/lib/thin/response.rb:90:in `each'
	/Library/Ruby/Gems/2.3.0/gems/thin-1.7.2/lib/thin/connection.rb:114:in `post_process'
	/Library/Ruby/Gems/2.3.0/gems/thin-1.7.2/lib/thin/connection.rb:50:in `block in process'
	/Library/Ruby/Gems/2.3.0/gems/eventmachine-1.2.5/lib/eventmachine.rb:1076:in `block in spawn_threadpool'```

Any idea why?

**Comment by pellens** [comment]
So, people having this problem: it happens when you have missing files (like scrips.js in my case). Adding the missing files solved it all...
